variable "component" {}
variable "env" {}
variable "engine" {}
variable "engine_version" {}
variable "database_name" {}
variable "subnet_ids" {}
variable "tags" {}
variable "kms_key_arn" {}
variable "instance_count" {}
variable "instance_class" {}
variable "vpc_id" {}
variable "sg_subnets_cidr" {}